### ISSUE TITLE
Permission from HTM for contribution

### ISSUE THREAD

**Issue by akarimso** [basil/byzantine-music#2]
Does each contributor need to obtain his own permission from Holy Transfiguration Monastery to use their translations?

**Comment by basil** [comment]
So far this hasn't been a big issue because the only things I've been working on recently have been HTM texts that have been in print for decades and are very widely disseminated (e.g. "It is truly meet", or the Paraklesis service) and thus don't represent any significant concern (i.e., don't represent a significant profit center for HTM), as well as because there is not much material here so far.

If we want to add material that has been recently published by HTM in the past few years, material that isn't very widely disseminated on the Internet, or a significant quantity of material, then this may be a potential source of concern (especially if it represents a significant profit center for HTM) so I would want to get permission from them first. I am already in contact with HTM and can discuss this privately with them, depending on the contribution.

**Comment by akarimso** [comment]
Ok. I don't have anything ready for contribution at the moment, but I will keep this in mind.
